version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sms_postgres
    environment:
      POSTGRES_DB: smsmerkezi
      POSTGRES_USER: admin_smsmerkezi
      POSTGRES_PASSWORD: wrpQuWwNR3EY
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: sms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sms_rabbitmq
    ports:
      - "5672:5672"   # AMQP protokolü
      - "15672:15672" # Yönetim arayüzü
    environment:
      RABBITMQ_DEFAULT_USER: admin_smsmerkezi
      RABBITMQ_DEFAULT_PASS: wrpQuWwNR3EY
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: 